### ISSUE TITLE
private route refresh kicks user back to Home page

### ISSUE THREAD

**Issue by bunsushi** [bunsushi/Gilgamesh-Versus#19]
If you refresh a PrivateRoute (e.g. Menu), you are kicked back to the Home log in/sign up page. This is more of a problem for protecting the Game route, because currently the gameOver method must reload the window to restart the level.

**Comment by bunsushi** [comment]
this problem is resolved with the current PrivateRoute class fix, although will need to be revisited after the full async solution is implemented.

**Comment by Joseph526** [comment]
This shouldn't change/revert after the full async solution is implemented. Closing.
